import type { OpeningKind, OpeningTypeDef, PanelId } from "../types/openings";

// Relative Richtungen statt Himmelsrichtungen (Jonas' Fehlerbericht
// 2026-07-23, siehe types/openings.ts) + Oben/Unten unveraendert. Alle
// sechs sind gueltige Durchbruch-Ziele.
export const PANEL_LABELS: Record<PanelId, string> = {
  front: "Vorne",
  back: "Hinten",
  left: "Links",
  right: "Rechts",
  top: "Oben",
  bottom: "Unten",
};

// Alle Masse in MILLIMETERN (Jonas' Vorgabe 2026-07-22). Tuer-Masse der
// Standardtueren sind LICHTE Durchgangsmasse (fertige nutzbare Oeffnung) -
// der tatsaechliche Wandausschnitt muesste in Wirklichkeit etwas groesser
// sein (Zargenzuschlag), das ist hier noch NICHT beruecksichtigt (kein
// Zuschlagswert vorgegeben) - siehe README.
export const OPENING_TYPES: Record<OpeningKind, OpeningTypeDef> = {
  door_single_1918: {
    kind: "door_single_1918",
    label: "Einzeltür 904 × 1918",
    category: "standard",
    shape: "rect",
    fixedWidth: 904,
    fixedHeight: 1918,
    minSize: 0,
    maxSize: 0,
    minBottomOffset: 170,
    minTopMargin: 150,
    hasHinge: true,
    verticalOnly: true,
    isDoor: true,
  },
  door_single_2418: {
    kind: "door_single_2418",
    label: "Einzeltür 904 × 2418",
    category: "standard",
    shape: "rect",
    fixedWidth: 904,
    fixedHeight: 2418,
    minSize: 0,
    maxSize: 0,
    minBottomOffset: 170,
    minTopMargin: 150,
    hasHinge: true,
    verticalOnly: true,
    isDoor: true,
  },
  door_double: {
    kind: "door_double",
    label: "Doppelflügeltür 2234 × 2530",
    category: "standard",
    shape: "rect",
    fixedWidth: 2234,
    fixedHeight: 2530,
    minSize: 0,
    maxSize: 0,
    minBottomOffset: 170,
    minTopMargin: 150,
    verticalOnly: true,
    isDoor: true,
  },
  door_custom_single: {
    kind: "door_custom_single",
    label: "Einzeltür (frei nach Maß)",
    category: "free",
    shape: "rect",
    defaultWidth: 904,
    defaultHeight: 1918,
    minWidth: 700,
    maxWidth: 1200,
    minHeight: 1900,
    maxHeight: 2600,
    minSize: 0,
    maxSize: 0,
    minBottomOffset: 170,
    minTopMargin: 150,
    hasHinge: true,
    verticalOnly: true,
    isDoor: true,
  },
  door_custom_double: {
    kind: "door_custom_double",
    label: "Doppelflügeltür (frei nach Maß)",
    category: "free",
    shape: "rect",
    defaultWidth: 2234,
    defaultHeight: 2530,
    minWidth: 1600,
    maxWidth: 3200,
    minHeight: 1900,
    maxHeight: 2700,
    minSize: 0,
    maxSize: 0,
    minBottomOffset: 170,
    minTopMargin: 150,
    verticalOnly: true,
    isDoor: true,
  },
  vent_weather: {
    kind: "vent_weather",
    label: "Wetterschutzgitter 411 × 411",
    category: "standard",
    shape: "rect",
    fixedWidth: 411,
    fixedHeight: 411,
    minSize: 0,
    maxSize: 0,
    protrusionDepth: 12,
  },
  cable: {
    kind: "cable",
    label: "Kabeldurchführung",
    category: "free",
    shape: "rect",
    defaultWidth: 100,
    defaultHeight: 100,
    minSize: 30,
    maxSize: 400,
  },
  pipe: {
    kind: "pipe",
    label: "Rohrdurchführung",
    category: "free",
    shape: "round",
    defaultWidth: 100,
    defaultHeight: 100,
    minSize: 50,
    maxSize: 500,
  },
};
